# nginx proxy address - http://172.17.0.1:59072

name: borg
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: borgwarehouse/borgwarehouse
    container_name: borg-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      - TZ=${TZ:-America/New_York}
      - NEXT_TELEMETRY_DISABLED=1
      - FQDN=${BASE_HOST_NAME:-$HOSTNAME}
      - CRONJOB_KEY=${APP_API_TOKEN:-gkRqUR9oqYEW6PuITE7t7kgh4vYi9IlM}
      - NEXTAUTH_URL=https://${BASE_HOST_NAME:-$HOSTNAME}
      - NEXTAUTH_SECRET=${APP_SECRET_KEY:-7itYVMQN2Bc2rVGffEI8PTv7cIYSjdZE}
      - MAIL_REJECT_SELFSIGNED_TLS=false
      - MAIL_SMTP_PORT=${MAIL_SMTP_PORT:-25}
      - MAIL_SMTP_HOST=${MAIL_SMTP_HOST:-172.17.0.1}
      - MAIL_SMTP_FROM=${MAIL_SMTP_FROM:-no-reply@${BASE_HOST_NAME:-$HOSTNAME}}
    ports:
      - '2222:22'
      - '172.17.0.1:59072:3000'
    volumes:
      - '/etc/ssh:/etc/ssh'
      - '/var/lib/srv/$USER/docker/borgwarehouse/rootfs/config/ssh:/home/borgwarehouse/.ssh'
      - '/var/lib/srv/$USER/docker/borgwarehouse/rootfs/config/borg:/home/borgwarehouse/app/config'
      - '/var/lib/srv/$USER/docker/borgwarehouse/rootfs/data/borg:/home/borgwarehouse/repos'
      - '/var/lib/srv/$USER/docker/borgwarehouse/rootfs/data/logs/borg:/home/borgwarehouse/logs'
    networks:
      - borg

  notify:
    image: caronc/apprise
    container_name: borg-notify
    hostname: borg-notify
    restart: always
    pull_policy: always
    logging: *default-logging
    user: 'www-data:www-data'
    environment:
      - TZ=${TZ:-America/New_York}
    networks:
      - borg

networks:
  borg:
    name: borg
    external: false
